
PROGRAM P10
IMPLICIT NONE
DOUBLE PRECISION, ALLOCATABLE :: U(:,:)
INTEGER :: I, J, L 
INTEGER, PARAMETER :: N = 100 
INTEGER, PARAMETER :: ITERATIONS = 2000 

OPEN(123,FILE="Potential.opju")

ALLOCATE(U(N,N))
U= 0.0
U(:,1) = 25
U(:,100)=25

DO L=1, ITERATIONS
 DO I=2, N-1
  DO J=2, N-1
   U(I,J,k) = (1.0/6.0)*(U(I,J+1,k)+U(I,J-1,k)+U(I+1,J,k)+U(I-1,J,k))
  END DO
 END DO
END DO

DO I=1, N
  DO J=1, N
 WRITE(123,"(100F30.15)") (U(I,J,k), k=1, N)
 end do
END DO

DEALLOCATE(U) !optional
CLOSE(123)
WRITE(*,*) "FINISHED"
STOP
END PROGRAM P10